#!/usr/bin/env python 3
#Hackkerrank - Python - Strings - sWAP cASE
#https://www.hackerrank.com/challenges/swap-case/problem
#Level: easy
#Points: 10

def swap_case(s):
    res=""
    for i in range(len(s.split())):
        for k in range(len(s.split()[i])):
            if (s.split()[i][k].islower()):
                res = res + s.split()[i][k].upper()
            else:
                res = res + s.split()[i][k].lower()
        res = res + " "
    return res

if __name__ == '__main__':
    s = 'HackerRank.com presents "Pythonist 2".'
    result = swap_case(s)
    print(result)
