#!/usr/bin/env python 3
#Hackkerrank - Python - Strings - Find a string
#https://www.hackerrank.com/challenges/find-a-string/problem
#Level: easy
#Points: 10

def count_substring(string, sub_string):
    res = 0
    for i in range(len(sub_string), len(string)+1):
        if(string[i-len(sub_string):i] == sub_string):
            res = res + 1    
    return res

if __name__ == '__main__':
    string = "ABCDCDC".strip()
    sub_string = "CDC".strip()
    
    count = count_substring(string, sub_string)
    print(count)
