#!/usr/bin/env python 
#Hackkerrank - Python - Strings - Alphabet Rangoli
#https://www.hackerrank.com/challenges/alphabet-rangoli/problem
#Level: easy
#Points: 20

def rowprint(size, row):
    I = list(range(-size, -size + row)) + list(range((size - row) + 2, size + 1))
    S=""
    for k in range(len(I)):
        S=S+chr(96 + abs(I[k]))
    S="-".join(S)
    print(S.center(4 * size - 3, '-'))

def print_rangoli(size):
    j = size

    for row in range(1, 2 * size):
        if (row < size):
            rowprint(size, row)
        elif(row == size):
            rowprint(size, row)
        elif(row > size):
            j = j - 1
            rowprint(size, j)
            
 if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)
