#!/usr/bin/env python
#Hackkerrank - Python - Numpy - Concatenate
#https://www.hackerrank.com/challenges/np-concatenate/problem
#Level: easy
#Points: 20

import numpy as np
a, b, c = map(int,input().split())
A = np.array([input().split() for _ in range(a)],int)
B = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((A, B), axis = 0))
