#!/usr/bin/env python
#Hackkerrank - Python - Numpy - Inner and Outer
#https://www.hackerrank.com/challenges/np-inner-and-outer/problem
#Level: easy
#Points: 20

import numpy
a = input().split()
b = input().split()
A = []
B = []

for k in range(len(a)):
    A.append(int(a[k]))

for k in range(len(b)):
    B.append(int(b[k]))
    
A=numpy.array(A)
B=numpy.array(B)

print(numpy.inner(A,B))
print(numpy.outer(A,B))
