#!/usr/bin/env python 3
#Hackkerrank - Python - Basic Data Types - Say "Hello, World!" With Python
#https://www.hackerrank.com/challenges/py-hello-world/problem
#Level: easy
#Points: 5

if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    print([ [i, j, k] for i in range( x + 1) for j in range( y + 1) for k in range(z + 1) if ( ( i + j + k) != n )])
