#!/usr/bin/env python 3
#Hackkerrank - Python - Basic Data Types - Find the runner up score
#https://www.hackerrank.com/challenges/swap-case/problem
#Level: easy
#Points: 10

res_arr = []

if __name__ == '__main__':
    n = int("5")
    arr = map(int, "2 3 6 6 5".split())
    
    mod_arr=(list(set(arr)))
    max_val = max(mod_arr)


    for k in range(len(mod_arr)):
        if(mod_arr[k] != max_val):
            res_arr.append(mod_arr[k])
    print(max(res_arr))
