#!/usr/bin/env python 3
#Hackkerrank - Python - Basic Data Types - Finding the percentage
#https://www.hackerrank.com/challenges/finding-the-percentage/problem
#Level: easy
#Points: 10

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    res = 0
    for k in range(len(student_marks[query_name])):
        res = res + student_marks[query_name][k]
    print("%.2f" % float(res/3))
