#!/usr/bin/env python
#Hackkerrank - Python - Introduction - If-Else
#https://www.hackerrank.com/challenges/py-if-else/problem
#Level: easy
#Points: 10

N = int(input())
if (N % 2 == 1):
    print("Weird")
else:
    if (N >= 2) and (N <= 5):
        print("Not Weird")
    elif (N >= 6) and (N <= 20):
        print("Weird")
    elif (N > 20):
        print("Not Weird")
