#!/usr/bin/env python
#Hackkerrank - Python - Introduction - Arithmetic Operators
#https://www.hackerrank.com/challenges/python-arithmetic-operators/problem
#Level: easy
#Points: 10

if __name__ == '__main__':
    a = int("3")
    b = int("2")
    
    print(a + b)
    print(a - b)
    print(a * b)
