#!/usr/bin/env python
#Hackkerrank - Python - Introduction - Division
#https://www.hackerrank.com/challenges/python-division/problem
#Level: easy
#Points: 10

if __name__ == '__main__':
    a = int("4")
    b = int("3")
    
    print(a // b)
    print(a / b)
