#!/usr/bin/env python
#Hackkerrank - Python - Introduction - Loops
#https://www.hackerrank.com/challenges/python-loops/problem
#Level: easy
#Points: 10

if __name__ == '__main__':
    n = int("5")
    for i in range(n):
        print(i ** 2)
