#!/usr/bin/env python
#Hackkerrank - Python - Introduction - Write a function
#https://www.hackerrank.com/challenges/write-a-function/problem
#Level: medium
#Points: 10

def is_leap(year):
    leap = False
    if (year % 4 == 0) and (year % 100 != 0):
        leap = True
        
    elif (year % 4 == 0) and (year % 100 == 0) and (year % 400 == 0):
        leap = True        
        
    elif (year % 4 == 0) and (year % 100 == 0):
        leap = False

    return leap

year = int(input())
print(is_leap(year))
